name: Test
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        id: check
        with:
          trigger: '#hello'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'