name: Test
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - uses: ./
        id: check
        with:
          trigger: '#hello'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'